# Generated by Django 3.1.4 on 2021-01-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('tittle', models.CharField(max_length=500)),
                ('head0', models.CharField(max_length=500)),
                ('chead0', models.CharField(max_length=5000)),
                ('head1', models.CharField(max_length=500)),
                ('chead1', models.CharField(max_length=5000)),
                ('head2', models.CharField(max_length=500)),
                ('chead2', models.CharField(max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnil', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
