# Generated by Django 3.1.4 on 2020-12-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zipCode',
            field=models.IntegerField(max_length=100),
        ),
    ]
